Feature/news reader
iankooo/news-reader pull request #3
Opened 2021-06-23 15:40 UTC by iankooo

2021-06-29 14:14 UTC, Misca requested changes
good job, just a couple of changes away

2021-06-29 14:14 UTC, Misca commented on app/src/main/java/com/schipala_ianko_radoslav/newsreader/feature/newsreaderlist/MainActivity.java
>  public class MainActivity extends AppCompatActivity {
let's rename this activity

2021-06-29 14:14 UTC, Misca commented on app/src/main/java/com/schipala_ianko_radoslav/newsreader/feature/newsreaderlist/model/NewsReaderViewModel.java
> +        //isLoading.set(false);
let's cleanup or start using these

2021-07-06 09:19 UTC, iankooo commented on app/src/main/java/com/schipala_ianko_radoslav/newsreader/feature/newsreaderlist/MainActivity.java
>  public class MainActivity extends AppCompatActivity {
done

2021-07-06 09:21 UTC, iankooo commented on app/src/main/java/com/schipala_ianko_radoslav/newsreader/feature/newsreaderlist/model/NewsReaderViewModel.java
> +        //isLoading.set(false);
done

2021-07-07 06:27 UTC, Misca approved these changes
GG 👍

2021-07-07 06:39 UTC, merged